### ISSUE TITLE
interact with a local file

### ISSUE THREAD

**Issue by francesco** [swank-js/swank-js#7]
I may be asking a stupid question, but I didn't manage to interact with a local file as done with the example in the tutorial test.html (accessed via the url "localhost:8009/swank-js/test.html"). Assuming I have an html file located at /path/to/local/file.html, what should I write in the url bar? If I use the target-url command specifying file:///path/to/local/file.html it doesn't seem to work, as I receive the message "WARNING: the URL must contain host and port" and pointing the browser to "localhost:8009" produces the message: "swank-js: unable to forward the request". Am I missing something? Btw, many thanks for the great tool!

**Comment by FrancescoRosi** [comment]
> I may be asking a stupid question, but I didn't manage to interact with a local file as done with the example in the tutorial test.html (accessed via the url "localhost:8009/swank-js/test.html"). Assuming I have an html file located at /path/to/local/file.html, what should I write in the url bar? If I use the target-url command specifying file:///path/to/local/file.html it doesn't seem to work, as I receive the message "WARNING: the URL must contain host and port" and pointing the browser to "localhost:8009" produces the message: "swank-js: unable to forward the request". Am I missing something? Btw, many thanks for the great tool!

Ciao Francesco, se non usi più questo account GitHub ti dispiacerebbe cambiare il tuo nome utente così posso avere io lo username @francesco? Grazie :) (purtroppo questa issue era l'unico modo che ho trovato per raggiungerti)

Hi Francesco, if you don't use this GitHub account anymore would you mind changing your username so I can get the @francesco username? Thanks :) (unfortunately this issue was the only way I found to reach you)
